[tool.ruff]
target-version = "py310"
<<<<<<< HEAD
line-length = 100
=======
line-length = 88
>>>>>>> origin/upstream-sim

[tool.ruff.lint]
select = ["B", "C4", "E", "F", "W"]
ignore = ["B007", "B008", "E501"]
ignore = ["B017", "E501", "W503"]
